baseURL = "http://acromondx.netlify.app"
languageCode = 'en-us'
title = 'AcromondX'
theme = 'zzo'

ignoreErrors = ["error-remote-getjson"]

[module]
  [module.hugoVersion]
    extended = true
    min = '0.111.0'